export const GET_TODO_LIST = 'GET_TODO_LIST'
export const UPDATE_NEW_TODO_NAME = 'UPDATE_NEW_TODO_NAME'
export const CLEAR_NEW_TODO_NAME = 'CLEAR_NEW_TODO_NAME'

export const IS_LOADING_TODOS = 'IS_LOADING_TODOS'

export const SHOW_INFO_NOTIFICATION = 'SHOW_INFO_NOTIFICATION'
export const SHOW_ERROR_NOTIFICATION = 'SHOW_ERROR_NOTIFICATION'
export const HIDE_NOTIFICATION = 'HIDE_NOTIFICATION'
